
TWIKI_USERNAME = ENV['WHITEBOARD_TWIKI_USERNAME'] || "AndrewCarengie"
TWIKI_PASSWORD = ENV['WHITEBOARD_TWIKI_PASSWORD'] || "password"
TWIKI_URL = ENV['WHITEBOARD_TWIKI_URL'] || 'http://info.sv.cmu.edu'

