development:
  host: anyhost
  username: anyone
  password: anysecret

test:
  host: anyhost
  username: anyone
  password: anysecret

production:
  host: anyhost
  username: anyone
  password: anysecret