development:
  twiki:
    username: None
    password: whatever
    url: http://a.domain.com
  adobe_connect:
    username: "an email address"
    password: "something"
    new_user_url: "htpp://a.domain.com"



     
test:
  twiki:
    username: None
    password: whatever
    url: http://a.domain.com
  adobe_connect:
    username: "an email address"
    password: "something"
    new_user_url: "htpp://a.domain.com"

production:
  twiki:
    username: None
    password: whatever
    url: http://a.domain.com
  adobe_connect:
    username: "an email address"
    password: "something"
    new_user_url: "htpp://a.domain.com"
