class AddPeopleFall2008IniStudents < ActiveRecord::Migration
  def self.up
    
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "SamerAbukhait", :first_name => "Samer", :last_name => "Abukhait", :webiso_account => "sabukhei@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/SamerAbukhait.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "KeyingBi", :first_name => "Keying", :last_name => "Bi", :webiso_account => "kbi@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/KeyingBi.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "SwetaDeivanayagam", :first_name => "Sweta", :last_name => "Deivanayagam", :webiso_account => "sdeivana@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/SwetaDeivanayagam.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "ChandaniDesai", :first_name => "Chandani", :last_name => "Desai", :webiso_account => "cddesai@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/ChandaniDesai.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "NishantDubey", :first_name => "Nishant", :last_name => "Dubey", :webiso_account => "ndubey@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/NishantDubey.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "DiwakarGoel", :first_name => "Diwakar", :last_name => "Goel", :webiso_account => "diwakarg@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/DiwakarGoel.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "InnocentHabiyaremye", :first_name => "Innocent", :last_name => "Habiyaremye", :webiso_account => "ihabiyar@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/InnocentHabiyaremye.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "ShriyaJoag", :first_name => "Shriya", :last_name => "Joag", :webiso_account => "sjoag@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/ShriyaJoag.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "MushabeBenjaminKags", :first_name => "Ben", :last_name => "Mushabe", :webiso_account => "mkags@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/MushabeBenjaminKags.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "AlainKajangwe", :first_name => "Alain", :last_name => "Kajangwe", :webiso_account => "akajangw@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/AlainKajangwe.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "EishaKher", :first_name => "Eisha", :last_name => "Kher", :webiso_account => "ekher@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/EishaKher.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "PatrickManiraho", :first_name => "Patrick", :last_name => "Maniraho", :webiso_account => "pmanirah@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/PatrickManiraho.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "JeanBaptisteMinani", :first_name => "Jean Baptiste", :last_name => "Minani", :webiso_account => "jminani@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/JeanBaptisteMinani.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "VedaMujumdar", :first_name => "Veda", :last_name => "Mujumdar", :webiso_account => "vmujumda@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/VedaMujumdar.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "AnushaNagarajan", :first_name => "Anusha", :last_name => "Nagarajan", :webiso_account => "anushan@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/AnushaNagarajan.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "PallaviPhadnis", :first_name => "Pallavi", :last_name => "Phadnis", :webiso_account => "pphadnis@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/PallaviPhadnis.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "RaunakRungta", :first_name => "Raunak", :last_name => "Rungta", :webiso_account => "rrungta@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/RaunakRungta.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "Paula HelenSaphir", :first_name => "Paula Helen", :last_name => "Saphir", :webiso_account => "psaphir@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/Paula HelenSaphir.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "NeethiShenoy", :first_name => "Neethi", :last_name => "Shenoy", :webiso_account => "nshenoy@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/NeethiShenoy.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "TyelisaShields", :first_name => "Tyelisa", :last_name => "Shields", :webiso_account => "tcshield@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/TyelisaShields.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "YashShroff", :first_name => "Yash", :last_name => "Shroff", :webiso_account => "yshroff@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/YashShroff.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "ParineetaSinha", :first_name => "Parineeta", :last_name => "Sinha", :webiso_account => "parineet@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/ParineetaSinha.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "AshishTulsiani", :first_name => "Ashish", :last_name => "Tulsiani", :webiso_account => "ashisht@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/AshishTulsiani.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "AbhishekVeldurthy", :first_name => "Abhishek", :last_name => "Veldurthy", :webiso_account => "aveldurt@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/AbhishekVeldurthy.jpg"
    Person.create :is_student => true, :is_part_time => false, :graduation_year => "2010", :masters_program => "INI", :masters_track => "IS", :twiki_name => "KazunoriTakeuchi", :first_name => "Kazunori", :last_name => "Takeuchi", :webiso_account => "ktakeuch@andrew.cmu.edu", :image_uri => "/images/students/2010/INI/KazunoriTakeuchi.jpg"
    
    end

  def self.down
  end
end
