class AddFAll2009IniStudents < ActiveRecord::Migration
  def self.up

Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"OmarAlrubaiyan", :first_name => "Omar", :last_name => "Alrubaiyan", :webiso_account => "oalrubai@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/OmarAlrubaiyan.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"HengTzeCheng", :first_name => "Paola", :last_name => "Boettner", :webiso_account => "pboettne@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/HengTzeCheng.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"Yan-TingChen", :first_name => "Yan-Ting", :last_name => "Chen", :webiso_account => "yantingc@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/Yan-TingChen.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"Yen-JuChen", :first_name => "Yen-Ju", :last_name => "Chen", :webiso_account => "yenjuc@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/Yen-JuChen.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ApinandDabpetch", :first_name => "Apinand", :last_name => "Dabpetch", :webiso_account => "adabpetc@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ApinandDabpetch.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"VinodEkambaram", :first_name => "Vinod", :last_name => "Ekambaram", :webiso_account => "vekambar@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/VinodEkambaram.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"HongGuo", :first_name => "Hong", :last_name => "Guo", :webiso_account => "hongguo@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/HongGuo.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"VivekHajela", :first_name => "Vivek", :last_name => "Hajela", :webiso_account => "vhajela@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/VivekHajela.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ChoromHamm", :first_name => "Chorom", :last_name => "Hamm", :webiso_account => "choromh@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ChoromHamm.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"Yu-ChengHuang", :first_name => "Yu-Cheng", :last_name => "Huang", :webiso_account => "yuchengh@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/Yu-ChengHuang.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"VamseeKandimalla", :first_name => "Vamsee", :last_name => "Kandimalla", :webiso_account => "vkandima@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/VamseeKandimalla.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"GenKazama", :first_name => "Gen", :last_name => "Kazama", :webiso_account => "gkazama@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/GenKazama.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ShuchenLi", :first_name => "Shuchen", :last_name => "Li", :webiso_account => "shuchenl@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ShuchenLi.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"Chih-HungLin", :first_name => "Chih-Hung", :last_name => "Lin", :webiso_account => "chihhunl@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/Chih-HungLin.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ArikMisler", :first_name => "Arik", :last_name => "Misler", :webiso_account => "amisler@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ArikMisler.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ShubhanshuNagar", :first_name => "Shubhanshu", :last_name => "Nagar", :webiso_account => "snagar@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ShubhanshuNagar.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"Luis AlbertoPerez Paz", :first_name => "Luis Alberto", :last_name => "Perez Paz", :webiso_account => "lperezpa@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/Luis AlbertoPerez Paz.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"FabianPopa", :first_name => "Fabian", :last_name => "Popa", :webiso_account => "fpopa@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/FabianPopa.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"SimonSibomana", :first_name => "Simon", :last_name => "Sibomana", :webiso_account => "ssiboman@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/SimonSibomana.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"KanupriyaTavri", :first_name => "Kanupriya", :last_name => "Tavri", :webiso_account => "ktavri@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/KanupriyaTavri.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"BryanThiry", :first_name => "Bryan", :last_name => "Thiry", :webiso_account => "bthiry@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/BryanThiry.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"GuntaweeTiwapong", :first_name => "Guntawee", :last_name => "Tiwapong", :webiso_account => "gthipman@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/GuntaweeTiwapong.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"NishantVerma", :first_name => "Nishant", :last_name => "Verma", :webiso_account => "nishantv@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/NishantVerma.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"HongkaiXing", :first_name => "Hongkai", :last_name => "Xing", :webiso_account => "hongkaix@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/HongkaiXing.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"RyanYang", :first_name => "Ryan", :last_name => "Yang", :webiso_account => "kaihsiay@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/RyanYang.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"RichYueh", :first_name => "Rich", :last_name => "Yueh", :webiso_account => "ryueh@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/RichYueh.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"ZhenZhang", :first_name => "Zhen", :last_name => "Zhang", :webiso_account => "zhenzhan@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/ZhenZhang.jpg"
Person.create :is_student => true, :is_part_time => false, :graduation_year => "2011", :masters_program => "INI", :twiki_name =>"XunZhou", :first_name => "Xun", :last_name => "Zhou", :webiso_account => "xunzhou@andrew.cmu.edu", :image_uri => "/images/students/INI/MSIT-21/XunZhou.jpg"


  end

  def self.down
  end
end
